spring:
  datasource:
    url: jdbc:mysql://10.222.1.51:3306/sqltest?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
  thymeleaf:
    suffix: .html
    check-template-location: true
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false
    mode: LEGACYHTML5


#    pagehelper.helper-dialect=mysql
#    pagehelper.params=count=countSql
#    pagehelper.reasonable=true
#    pagehelper.support-methods-arguments=true
pagehelper:
  helper-dialect: mysql
  params: params=count=countSql
  reasonable: true
  support-methods-arguments: true


